networks:
  macvlan_proxy:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fc00:0:0:1::/64
        - subnet: 172.128.2.0/24
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ${CONFIG_PATH}/heimdall:/config
    ports:
      - 61211:80
      - 60211:443
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.11
    dns:
      - ${DOCKER_DNS}
  portainer:
    image: 6053537/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/portainer:/data
    ports:
      - 60212:9000
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.12
    dns:
      - ${DOCKER_DNS}
      
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 60213:8191
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.13
    dns:
      - ${DOCKER_DNS}
      
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - 60223:9696
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.23
    dns:
      - ${DOCKER_DNS}
      
  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jproxy/database:/app/database
    ports:
      - 60215:8117
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.15
    dns:
      - ${DOCKER_DNS}
      
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - JELLYFIN_TYPE=emby
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/app/config
    ports:
      - 60216:5055
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.16
    depends_on:
      - sonarr
      - radarr
    dns:
      - ${DOCKER_DNS}
      
  radarr:
    image: linuxserver/radarr:5.2.6
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60217:7878
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.17
    depends_on:
      - jproxy
      - qbittorrent
    dns:
      - ${DOCKER_DNS}
      
  sonarr:
    image: linuxserver/sonarr:4.0.0
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60218:8989
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.18
    depends_on:
      - jproxy
      - qbittorrent
    dns:
      - ${DOCKER_DNS}
      
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=60219
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60219:60219
      - 60881:6881
      - 60881:6881/udp
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.19
        ipv6_address: fc00:0:0:1::a
    dns:
      - ${DOCKER_DNS}
      
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    container_name: chinesesubfinder
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}/chinesesubfinder:/config
      - ${MEDIA_PATH}:/media/video
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PERMS=true
      - UMASK=022
    hostname: chinesesubfinder
    ports:
      - 60221:19035
      - 19037:19037
    logging:
        driver: "json-file"
        options:
          max-size: "100m"
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.21
    dns:
      - ${DOCKER_DNS}
      
  emby:
    image:  lscr.io/linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - GIDLIST=0
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/emby:/config
      - ${MEDIA_PATH}:/media/video
    ports:
      - 60220:8096
    networks:
      macvlan_proxy:
        ipv4_address: 172.128.2.20
    devices:
      - /dev/dri:/dev/dri
    dns:
      - ${DOCKER_DNS}

